const PUBLIC_API_ENDPOINT = process.env.REACT_APP_PUBLIC_API_ENDPOINT;
const PUBLIC_PRIVATE_TEST_CODE = process.env.REACT_APP_PUBLIC_PRIVATE_TEST_CODE;

export {
  PUBLIC_PRIVATE_TEST_CODE,
  PUBLIC_API_ENDPOINT,
};

 
 