apiVersion: v1
kind: Service
metadata:
  annotations:
    linkerd.io/inject: enabled
  name: fe-admin
  labels:
    app: fe-admin
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: fe-admin
