name: 01.deploy-develop

on:
  workflow_dispatch:
    inputs:
      confirmDeployment:
        description: 'Confirm Deployment'
        required: true
env:
  SERVER_IP: "devcab.org"
  SERVER_USER: "ubuntu"

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
              mkdir -p ~/.ssh
              echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
              chmod 600 ~/.ssh/id_rsa
              ssh-keyscan -t rsa @$SERVER_IP >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          ssh -i ~/.ssh/id_rsa $SERVER_USER@@$SERVER_IP 'sudo docker kill cab-client-2024'
          ssh -i ~/.ssh/id_rsa $SERVER_USER@@$SERVER_IP 'sudo docker rm cab-client-2024'
          ssh -i ~/.ssh/id_rsa $SERVER_USER@@$SERVER_IP 'sudo docker pull warjamma/cab-client-2024:latest'
          ssh -i ~/.ssh/id_rsa $SERVER_USER@@$SERVER_IP 'sudo docker run -d -p 3000:80 --name cab-client-2024 warjamma/cab-client-2024:latest'