name: 01.development
on:
  workflow_dispatch:
    inputs:
      confirmDeployment:
        description: 'Confirm Deployment'
        required: true
env:
  DEPLOYMENT_NAME: cab-client
  IMAGE: cab-client
  OVERLAY_DIR: ./k8s/overlays/development
  INGRESS_IP: 35.186.147.166
  DOT_ENV_FILE_NAME: .env.develop
jobs:
  variables:
    name: setup variable
    runs-on: ubuntu-latest
    outputs:
      DEPLOYMENT_NAME: ${{ env.DEPLOYMENT_NAME }}
      IMAGE: ${{ env.IMAGE }}
      OVERLAY_DIR: ${{ env.OVERLAY_DIR }}
      INGRESS_IP: ${{ env.INGRESS_IP }}
      DOT_ENV_FILE_NAME: ${{ env.DOT_ENV_FILE_NAME }}
    steps:
      - name: Echo
        run: echo prepare variable
  cab-client:
    needs: variables
    name: deploy cab-client
    uses: ./.github/workflows/00.gke-deployment.yml
    with:
      DEPLOYMENT_NAME: ${{ needs.variables.outputs.DEPLOYMENT_NAME }}
      IMAGE: ${{ needs.variables.outputs.IMAGE }}
      OVERLAY_DIR: ${{ needs.variables.outputs.OVERLAY_DIR }}
      INGRESS_IP: ${{ needs.variables.outputs.INGRESS_IP }}
