name: 03.ssh-development

on:
  workflow_dispatch:
    inputs:
      confirmDeployment:
        description: 'Confirm Deployment'
        required: true
env:
  SERVER_IP: "devcab.org"
  SERVER_USER: "ubuntu"
  SERVER_PORT: "22"
  SERVER_DEST_PATH: "/home/ubuntu/cab-client-2024"

jobs: 
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Configuration env
        run: echo "${{ secrets.ENV }}" | tr -d '\r' > /home/runner/work/cab-client-2024/cab-client-2024/.env.develop

      - name: Install Dependencies
        run: yarn install

      - name: Build Application
        run: yarn build

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
      - name: Deploy
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" --progress /home/runner/work/cab-client-2024/cab-client-2024/ $SERVER_USER@$SERVER_IP:$SERVER_DEST_PATH
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP 'sudo systemctl restart cab-client.service' || exit 1
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP 'sudo journalctl -xe | grep cab-client.service' || exit 1
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP 'sudo systemctl status cab-client.service' || exit 1